import React, {useState, useEffect, useRef} from "react";
import {useParams, useNavigate} from "react-router-dom";
import "./LightMode.css";

const LightMode = () => {
    const navigate = useNavigate();
    const form = useRef();
    const [showQuestions, setShowQuestions] = useState(false);

    const redirectBack = (e) => {
        e.preventDefault();
        navigate('/');
    }

    return(
      <div className = "light-mode">
            <body>
                <div class="site">
                    <div id="page">
                        <h1>Light Mode</h1>
                        <br></br>
                        <p>Please read the following passage. When you have finished reading, please click on the button to reveal three questions; type your answer in the provided boxes.</p>
                        <br></br>
                        <h1>What Do We Mean by Leadership?</h1>
                        <p>Hughes, R., Ginnett, R., & Curphy, G. (2015). Leadership: Enhancing the Lessons of Experience. Chapter 1.</p>
                        <br></br>

                        <h2>Introduction</h2>
                        <p>In the spring of 1972, an airplane flew across the Andes mountains carrying its crew and 40 passengers. Most of the passengers were members of an amateur Uruguayan rugby team en route to a game in Chile. The plane never arrived. It crashed in snow-covered mountains, breaking into several pieces on impact. The main part of the fuselage slid like a toboggan down a steep valley, coming to rest in waist-deep snow. Although a number of people died immediately or within a day of the impact, the picture for the 28 survivors was not much better. The fuselage offered little protection from the extreme cold, food supplies were scant, and a number of passengers had serious injuries from the crash. Over the next few days, several surviving passengers became psychotic and several others died from their injuries. The passengers who were relatively uninjured set out to do what they could to improve their chances of survival.</p>
                        <p>Several worked on “weatherproofing” the wreckage; others found ways to get water; and those with medical training took care of the injured. Although shaken by the crash, the survivors initially were confident they would be found. These feelings gradually gave way to despair as search and rescue teams failed to find the wreckage. With the passing of several weeks and no sign of rescue in sight, the remaining passengers decided to mount expeditions to determine the best way to escape. The most physically fit were chosen to go on the expeditions because the thin mountain air and the deep snow made the trips difficult. The results of the trips were both frustrating and demoralizing: the expedition members determined they were in the middle of the Andes mountains, and walking out to find help was believed to be impossible. Just when the survivors thought nothing worse could possibly happen, an avalanche hit the wreckage and killed several more of them.</p>
                        <p>The remaining survivors concluded they would not be rescued, and their only hope was for someone to leave the wreckage and find help. Three of the fittest passengers were chosen for the final expedition, and everyone else’s work was directed toward improving the expedition’s chances of success. The three expedition members were given more food and were exempted from routine survival activities; the rest spent most of their energies securing supplies for the trip. Two months after the plane crash, the expedition members set out on their final attempt to find help. After hiking for 10 days through some of the most rugged terrain in the world, the expedition stumbled across a group of Chilean peasants tending cattle. One of the expedition members stated, “I come from a plane that fell in the mountains. I am Uruguayan . . .” Eventually 14 other survivors were rescued.</p>
                        <p>When the full account of their survival became known, it was not without controversy. It had required extreme and unsettling measures: the sur vivors had lived only by eating the flesh of their deceased comrades. Nonetheless, their story is one of the most moving survival dramas of all time, magnificently told by Piers Paul Read in <i>Alive</i>. It is a story of tragedy and courage, and it is a story of leadership.</p>
                        <p>Perhaps a story of survival in the Andes is so far removed from everyday experience that it does not seem to hold any relevant lessons about leadership for you personally. But consider some of the basic issues the Andes survivors faced: tension between individual and group goals, dealing with the different needs and personalities of group members, and keeping hope alive in the face of adversity. These issues are not so different from those facing many groups we’re a part of. We can also look at the Andes experience for examples of the emergence of informal leaders in groups. Before the flight, a boy named Parrado was awkward and shy, a “second-stringer” both athletically and socially. Nonetheless, this unlikely hero became the best loved and most respected among the survivors for his courage, optimism, fairness, and emotional support. Persuasiveness in group decision making also was an important part of leadership among the Andes survivors. During the difficult discussions preceding the agonizing decision to survive on the flesh of their deceased comrades, one of the rugby players made his reasoning clear: “I know that if my dead body could help you stay alive, then I would want you to use it. In fact, if I do die and you don’t eat me, then I’ll come back from wherever I am and give you a good kick in the ass.”</p>
                        <h2>What Is Leadership?</h2>
                        <p>The Andes story and the experiences of many other leaders we’ll introduce to you in a series of profiles sprinkled throughout the chapters provide numerous examples of leadership. But just what <i>is</i> leadership? People who do research on leadership disagree more than you might think about what leadership really is. Most of this disagreement stems from the fact that <b>leadership</b> is a complex phenomenon involving the leader, the followers, and the situation. Some leadership researchers have focused on the personality, physical traits, or behaviors of the leader; oth ers have studied the relationships between leaders and followers; still oth ers have studied how aspects of the situation affect how leaders act. Some have extended the latter viewpoint so far as to suggest there is no such thing as leadership; they argue that organizational successes and failures often get falsely attributed to the leader, but the situation may have a much greater impact on how the organization functions than does any individual, including the leader.</p>
                        <p>Perhaps the best way for you to begin to understand the complexities of leadership is to see some of the ways leadership has been defined. Leadership researchers have defined leadership in many different ways:</p>
                        <ul class="ul-regular">
                            <li>The process by which an agent induces a subordinate to behave in a desired manner.</li>
                            <li>Directing and coordinating the work of group members.</li>
                            <li>An interpersonal relation in which others comply because they want to, not because they have to.</li>
                            <li>The process of influencing an organized group toward accomplishing its goals.</li>
                            <li>Actions that focus resources to create desirable opportunities.</li>
                            <li>Creating conditions for a team to be effective.</li>
                            <li>The ability to get results and the ability to build teams; these represent the what and the how of leadership.</li>
                            <li>A complex form of social problem solving.</li>
                        </ul>
                        <p>As you can see, definitions of leadership differ in many ways, and these differences have resulted in various researchers exploring disparate aspects of leadership. For example, if we were to apply these definitions to the Andes survival scenario described earlier, some researchers would focus on the behaviors Parrado used to keep up the morale of the survivors. Researchers who define leadership as influencing an organized group toward accomplishing its goals would examine how Parrado managed to convince the group to stage and support the final expedition. One’s definition of leadership might also influence just who is considered an appropriate leader for study. Thus each group of researchers might focus on a different aspect of leadership, and each would tell a different story regarding the leader, the followers, and the situation.</p>
                        <p>Although having many leadership definitions may seem confusing, it is important to understand that there is no single correct definition. The various definitions can help us appreciate the multitude of factors that affect leadership, as well as different perspectives from which to view it. For example, in the first definition just listed, the word <i>subordinate</i> seems to confine leadership to downward influence in hierarchical relationships; it seems to exclude informal leadership. The second definition emphasizes the directing and controlling aspects of leadership, and thereby may deemphasize emotional aspects of leadership. The emphasis placed in the third definition on subordinates’ “wanting to” comply with a leader’s wishes seems to exclude any kind of coercion as a leadership tool. Further, it becomes problematic to identify ways in which a leader’s actions are really leadership if subordinates voluntarily comply when a leader with considerable potential coercive power merely asks others to do something without explicitly threatening them. Similarly, a key reason behind using the phrase <i>desirable opportunities</i> in one of the definitions was precisely to distinguish between leadership and tyranny. And partly because there are many different definitions of leadership, there is also a wide range of individuals we consider leaders. In addition to stories about leaders and lead ership we will sprinkle through this book, we will highlight several in each chapter in a series of Profiles in Leadership. The first of these is Profiles in Leadership 1.1, which highlights Peter Jackson.</p>
                        <p>All considered, we find that defining leadership as “the process of influencing an organized group toward accomplishing its goals” is fairly comprehensive and helpful. Several implications of this definition are worth further examination.</p>
                        <div class="highlight-box">
                            <h4>Peter Jackson</h4>
                            <p><b>PROFILES IN LEADERSHIP 1.1</b></p>
                            <p>When Peter Jackson read <i>The Lord of the Rings</i> trilogy at the age of 18, he couldn’t wait until it was made into a movie; 20 years later he made that movie himself. In 2004 <i>The Lord of the Rings: The Return of the King</i> took home 11 Academy Awards, winning the Oscar in every category for which it was nominated. This tied the record for the most Oscars ever earned by one motion picture. Such an achievement might seem unlikely for a producer/director whose film debut was titled <i>Bad Taste</i>, which it and subse quentworks exemplified in spades. Peter Jackson made horror movies so grisly and revolting that his fans nicknamed him the “Sultan of Splatter.” Nonetheless, his talent was evident to discerning eyes—at least among horror film aficionados. <i>Bad Taste</i> was hailed as a cult classic at the Cannes Film Festival, and horror fans tabbed Jackson as a talent to follow.</p>
                            <p>When screenwriter Costa Botes heard that <i>The Lord of the Rings</i> would be made into a live action film, he thought those responsible were crazy. Prevailing wisdom was that the fantastic and complex trilogy simply could not be believably translated onto the screen. But he also believed that “there was no other director on earth who could do it justice”. And do it justice he obviously did. What was it about the “Sultan of Splatter’s” leadership that gave others such confidence in his ability to make one of the biggest and best movies of all time? What gave him the confidence to even try? And what made others want to share in his vision?</p>
                            <p>Peter Jackson’s effectiveness as a leader has been due in large part to a unique combination of personal qualities and talents. One associate, for example, called him “one of the smartest people I know,” as well as a maverick willing to buck the establishment. Jackson is also a tireless worker whose early successes were due in no small part to the combination of his ambition and dogged perseverance. His initial success was driven largely by his budding genius in making films on a low budget and with virtually no other staff. In reading others’ comments who worked with him on the <i>LOTR</i> project, however, it’s clear that his leadership continued to develop over the years. It was his ability to communicate a shared vision and inspire such extraordinary work from an incredibly large staff that made <i>LOTR</i> so spectacularly successful.</p>
                            <p>Not one to rest on his laurels, in 2012 Jackson released the first installment of <i>The Hobbit</i>, another technologically standard-breaking and popular film trilogy.</p>
                        </div>
                        <h3>Leadership Is Both a Science and an Art</h3>
                        <p>Any fool can keep a rule. God gave him a brain to know when to break the rule. General Willard W. Scott  Saying leadership is both a science and an art emphasizes the subject of leadership as a field of scholarly inquiry, as well as certain aspects of the practice of leadership. The scope of the science of leadership is reflected in the number of studies—approximately 8,000—cited in an authoritative reference work, <i>Bass & Stogdill’s Handbook of Leadership: Theory, Research, and Managerial Applications</i>. However, being an expert on leadership research is neither necessary nor sufficient for being a good leader. Some managers may be effective leaders without ever having taken a course or training program in leadership, and some scholars in the field of leadership may be relatively poor leaders themselves.</p>
                        <p>However, knowing something about leadership research is relevant to leadership effectiveness. Scholarship may not be a prerequisite for leadership effectiveness, but understanding some of the major research findings can help individuals better analyze situations using a variety of perspectives. That, in turn, can tell leaders how to be more effective. Even so, because skills in analyzing and responding to situations vary greatly across leaders, leadership will always remain partly an art as well as a science. Highlight 1.1 provides further perspective on how the art and science of leadership are represented in somewhat distinctive research traditions.</p>
                        <div class="highlight-box">
                            <h4>The Academic and Troubadour Traditions of Leadership Research</h4>
                            <p><b>HIGHLIGHT 1.1</b></p>
                            <p>On a practical level, leadership is a topic that almost everyone is interested in at one time or another. People have a vested interest in who is running their government, schools, company, or church, and because of this interest thousands of books and articles have been written about the topic of leadership. Curphy and Hogan believe these works can be divided into two major camps. The <b>academic tradition</b> consists of articles that use data and statistical techniques to make inferences about effective leadership. Because the academic tradition is research based, for the most part these findings are written for other leadership researchers and are virtually uninterpretable to leadership <i>practitioners</i>. As such, leadership practitioners are often unfamiliar with the research findings of the academic tradition.</p>
                            <p>The second camp of leadership literature is the <b>troubadour tradition</b>. These books and articles often consist of nothing more than the opinions or score-settling reminiscences of former leaders. Books in the troubadour tradition, such as <i>Who Moved My Cheese?</i>, <i>What the CEO Wants You to Know</i>, <i>Winning, and Lead Like Jesus: Lessons from the Greatest Leadership Role Model of all Time</i>, are wildly popular, but it is difficult to separate fact from fiction or determine whether these opinions translate to other settings. People who are unfamiliar with the findings of the academic tradition and the limitations of the troubadour tradition find it difficult to differentiate research findings from opinion.</p>
                            <p>Perhaps the biggest challenge to improving the practice of leadership is to give practitioners timely, easily digestible, research-grounded advice on how to effectively lead others. The knowledge accumulated from 90 years of leadership research is of tremendous value, yet scientists have paid little attention to the ultimate consumers of their work—leaders and leaders-to-be. Leadership practitioners often want fast answers about how to be more effective or successful and understandably turn to popular books and articles that <i>appear</i> to provide timely answers to their practical concerns. Unfortunately, however, the claims in the popular literature are rarely based on sound research; they oversimplify the complexities of the leadership process; and many times they actually offer bad advice. Relatively little weight is given to well-researched leadership studies, primarily because the arcane requirements of publishing articles in scholarly journals make their content virtually unreadable (and certainly uninteresting) to actual leadership practitioners. One of the primary objectives of this book is to make the results of leadership research more usable for leaders and leaders-to-be.</p>
                        </div>
                        <h3>Leadership Is Both Rational and Emotional</h3>
                        <p>Leadership involves both the rational and emotional sides of human experience. Leadership includes actions and influences based on reason and logic as well as those based on inspiration and passion. We do not want to cultivate merely intellectualized leaders who respond with only logical predictability. Because people differ in their thoughts and feelings, hopes and dreams, needs and fears, goals and ambitions, and strengths and weaknesses, leadership situations can be complex. People are both rational and emotional, so leaders can use rational techniques and emotional appeals to influence followers, but they must also weigh the rational and emotional consequences of their actions.</p>
                        <p>A full appreciation of leadership involves looking at both these sides of human nature. Good leadership is more than just calculation and planning, or following a checklist, even though rational analysis can enhance good leadership. Good leadership also involves touching others’ feelings; emotions play an important role in leadership too. Just one example of this is the civil rights movement of the 1960s, which was based on emotions as well as on principles. Dr. Martin Luther King Jr. inspired many people to action; he touched people’s hearts as well as their heads.</p>
                        <p>Aroused feelings, however, can be used either positively or negatively, constructively or destructively. Some leaders have been able to inspire others to deeds of great purpose and courage. On the other hand, as images of Adolf Hitler’s mass rallies or present-day angry mobs attest, group frenzy can readily become group mindlessness. As another example, emotional appeals by the Reverend Jim Jones resulted in approximately 800 of his followers volitionally committing suicide.</p>
                        <p>The mere presence of a group (even without heightened emotional levels) can also cause people to act differently than when they are alone. For example, in airline cockpit crews, there are clear lines of authority from the captain down to the first officer (second in command) and so on. So strong are the norms surrounding the authority of the captain that some first officers will not take control of the airplane from the captain even in the event of impending disaster. Foushee reported a study wherein airline captains in simulator training intentionally feigned incapacitation so the response of the rest of the crew could be observed. The feigned incapacitations occurred at a predetermined point during the plane’s final approach in landing, and the simulation involved conditions of poor weather and visibility. Approximately 25 percent of the first officers in these simulated flights allowed the plane to crash. For some reason, the first officers did not take control even when it was clear the captain was allowing the aircraft to deviate from the parameters of a safe approach. This example demonstrates how group dynamics can influence the behavior of group members even when emotional levels are <i>not</i> high. (Believe it or not, airline crews are so well trained that this is <i>not</i> an emotional situation.) In sum, it should be apparent that leadership involves followers’ feelings and nonrational behavior as well as rational behavior. Leaders need to consider <i>both</i> the rational and the emotional consequences of their actions.</p>
                        <h3>Leadership and Management</h3>
                        <p>In trying to answer “What is leadership?” it is natural to look at the relationship between leadership and management. To many, the word <b>management</b> suggests words like <i>efficiency</i>, <i>planning</i>, <i>paperwork</i>, <i>procedures</i>, <i>regulations</i>, <i>control</i>, and <i>consistency</i>. Leadership is often more associated with words like <i>risk taking</i>, <i>dynamic</i>, <i>creativity</i>, <i>change</i>, and <i>vision</i>. Some say leadership is fundamentally a value-choosing, and thus a value-laden, activity, whereas management is not. Leaders are thought to <i>do the right things</i>, whereas managers are thought to <i>do things right</i>. Here are some other distinctions between managers and leaders:</p>
                        <ul class="ul-regular">
                            <li>Managers administer; leaders innovate.</li>
                            <li>Managers maintain; leaders develop.</li>
                            <li>Managers control; leaders inspire.</li>
                            <li>Managers have a short-term view; leaders, a long-term view.</li>
                            <li>Managers ask how and when; leaders ask what and why.</li>
                            <li>Managers imitate; leaders originate.</li>
                            <li>Managers accept the status quo; leaders challenge it.</li>
                        </ul>
                        <p>Zaleznik goes so far as to say these differences reflect fundamentally different personality types: leaders and managers are basically different kinds of people. He says some people are managers by <i>nature</i>; other people are leaders <i>by nature</i>. One is not better than the other; they are just different. Their differences, in fact, can be useful because organizations typically need both functions performed well. For example, consider again the U.S. civil rights movement in the 1960s. Dr. Martin Luther King Jr. gave life and direction to the civil rights movement in America. He gave dignity and hope of freer participation in national life to people who before had little reason to expect it. He inspired the world with his vision and eloquence, and he changed the way we live together. America is a different nation today because of him. Was Dr. Martin Luther King Jr. a leader? Of course. Was he a manager? Somehow that does not seem to fit, and the civil rights movement might have failed if it had not been for the managerial talents of his supporting staff. Leadership and management complement each other, and both are vital to organizational success.</p>
                        <div class="highlight-box">
                            <h4>The Response of Leadership to a Natural Disaster</h4>
                            <p><b>HIGHLIGHT 1.2</b></p>
                            <p>Much has been written about the inadequate response of local, state, and federal agencies to Hurricane Katrina. It may be instructive to compare the response of government agencies to a natural disaster on a different coast a century earlier: the San Francisco earthquake and fire of 1906.</p>
                            <p>While the precipitant disaster was the earthquake itself, much destruction resulted from the consequent fire, one disaster aggravating the impact of the other. Because of the earthquake, utility poles throughout the city fell, taking the high- tension wires they were carrying with them. Gas pipes broke; chimneys fell, dropping hot coals into thousands of gallons of gas spilled by broken fuel tanks; stoves and heaters in homes toppled over; and in moments fires erupted across the city. And because the earthquake’s first tremors also broke water pipes throughout the city, fire hydrants everywhere suddenly went dry, making fighting the fires virtually impossible. In objective terms, the disaster is estimated to have killed as many as 3,000 people, rendered more than 200,000 homeless, and by some measures caused $195 billion in property loss as measured by today’s dollars.</p>
                            <p>How did authorities respond to the crisis when there were far fewer agencies with presumed response plans to combat disasters, and when high-tech communication methods were unheard of? Consider these two examples:</p>
                            <ul class="ul-regular">
                                <li>The ranking officer assigned to a U.S. Army post in San Francisco was away when the earthquake struck, so it was up to his deputy to help organize the army’s and federal government’s response. The deputy immediately cabled Washington, D.C., requesting tents, rations, and medicine. Secretary of War William Howard Taft, who would become the next U.S. president, responded by immediately dispatching 200,000 rations from Washington State. In a matter of days, every tent in the U.S. Army had been sent to San Francisco, and the longest hospital train in history was dispatched from Virginia.</li>
                                <li>Perhaps the most impressive example of leadership initiative in the face of the 1906 disaster was that of the U.S. Post Office. It recovered its ability to function in short order without losing a single item that was being handled when the earthquake struck. And because the earthquake had effectively destroyed the city’s telegraphic connection (telegrams inside the city were temporarily being delivered by the post office), a critical question arose: How could people struck by the disaster communicate with their families elsewhere? The city postmaster immediately announced that all citizens of San Francisco could use the post office to inform their families and loved ones of their condition and needs. He further stipulated that for outgoing private letters <i>it would not matter whether the envelopes bore stamps</i>. This was what was needed: Circumstances demanded that people be able to communicate with friends and family whether or not they could find or pay for stamps.</li>
                            </ul>
                            <p>Perhaps this should remind us that modern leadership is not necessarily better leadership, and that leadership in government is not always bureaucratic and can be both humane and innovative.</p>
                        </div>
                        <p>With regard to the issue of leadership versus management, the authors of this book take a middle-of-the-road position. We think of leadership and management as closely related but distinguishable functions. Our view of the relationship that leadership and management are two overlapping functions. Although some functions performed by leaders and managers may be unique, there is also an area of overlap. In reading Highlight 1.2, did you see more good management in the response to the 1906 San Francisco earthquake, more good leader ship, or both?</p>
                        <div class="highlight-box">
                            <h4>The Romance of Leadership</h4>
                            <p><b>HIGHLIGHT 1.3</b></p>
                            <p>This text is predicated on the idea that leaders can make a difference. Interestingly, though, while businesspeople generally agree, not all scholars do.</p>
                            <p>People in the business world attribute much of a company’s success or failure to its leadership. One study counted the number of articles appearing in <i>The Wall Street Journal</i> that dealt with leadership and found nearly 10 percent of the articles about representative target companies addressed that company’s leadership. Furthermore, there was a significant positive relationship between company performance and the number of articles about its leadership; the more a company’s leadership was emphasized in <i>The Wall Street Journal</i>, the better the company was doing. This might mean the more a company takes leadership seriously (as reflected by the emphasis in <i>The Wall Street Journal</i>), the better it does.</p>
                            <p>However, the study authors were skeptical about the real utility of leadership as a concept. They suggested leadership is merely a romanticized notion—an obsession people want and need to believe in. Belief in the potency of leadership may be a cultural myth that has utility primarily insofar as it affects how people create meaning about causal events in complex social systems. The behavior of leaders, the authors contend, does not account for much of the variance in an organization’s performance. Nonetheless, people seem strongly committed to a basic faith that individual leaders shape organizational destiny for good or ill.</p>
                            <p>As you read this book and come to appreciate how many factors affect a group’s success <i>besides</i> the talents of the individual leader, you might pay a price for that understanding. As you appreciate the <i>complexity</i> of leadership more, the <i>romance</i> of leadership might slightly diminish.</p>
                        </div>

                        <button 
                            onClick={() => setShowQuestions(true)}
                            className="show-questions-btn"
                            style={{ display: showQuestions ? 'none' : 'block' }}
                            >
                            Show Questions
                        </button>
                        {showQuestions && (
                            <form ref={form} onSubmit={redirectBack}>
                                <label><strong>Question 1: </strong>Does leadership seem more like an art or a science to you?</label><br></br>
                                <input type="text" name="q1"></input><br></br><br></br>
                                <label><strong>Question 2: </strong>What is one distinction we typically make between a manager and a leader?</label><br></br>
                                <input type="text" name="q2"></input><br></br><br></br>
                                <label><strong>Question 3: </strong>Who is one leader you look up to?</label><br></br>
                                <input type="text" name="q3"></input><br></br><br></br>

                                <input type="submit" value="Submit Answers"/>
                                <br></br><br></br>
                            </form>
                        )}
                    </div>
                </div>
            </body>
      </div>
    )
  };
  
  export default LightMode;